version: "3.8"

services:
  db:
    image: postgres:16.1
    container_name: PostgreSQL
    restart: on-failure
    environment:
      POSTGRES_DB: mmu
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5443:5443"
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
  bot:
    build: .
    container_name: Bot
    command: sh -c "python app"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      PG_URL: ${PG_URL}
    restart: always
    depends_on:
      - db


volumes:
  pgdata:
  pgadmin:
