version: "3.8"

services:
  database:
    container_name: PostgreSQL
    image: postgres:16
    restart: on-failure
    volumes:
      - ./mmu_db_init.sql:/docker-entrypoint-initdb.d/mmu_db_init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=vityooook@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=v15122003
    ports:
      - "5050:80"
    depends_on:
      - database
  bot:
    build: .
    command:
      - sh -c "python -m main_tg.py"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - database


volumes:
  pgdata:
